services:
  postgres:
    image: postgres:16
    container_name: tavros-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tavros-db
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
volumes:
  postgres_data:
  